---
title: "multilevel tadpoles"
output: html_document
---

```{r install packages and load library and data}
#follow instructions in this page: https://github.com/rmcelreath/rethinking
#install C++ toolchain
#install.packages(c("coda","mvtnorm","devtools","loo","dagitty","shape"))
#install.packages("cmdstanr", repos = c("https://stan-dev.r-universe.dev", getOption("repos")))
#cmdstanr::install_cmdstan()
#pak::pak("rmcelreath/rethinking")
```

```{r load the frog data}
library(rethinking)
data(reedfrogs)
d <- reedfrogs
str(d)
```

```{r make the tank cluster available}
d$tank <- 1:nrow(d)

dat <- list(
  S = d$surv,
  N = d$density,
  tank= d$tank
)
```

```{r approximate posterior}
#install_cmdstan()
m13.1 <- ulam(
  alist(
    S ~ dbinom( N , p ) ,
    logit(p) <- a[tank] ,
    a[tank] ~ dnorm( 0, 1.5 )
  ), data=dat, chains=4, log_lik=TRUE )

```

```{r inspect the posterior - no memory}
precis(m13.1, depth=2)
```

```{r adaptively pools information across tanks}
# Make the prior for the alpha function of some new parameters and compute the posterior
m13.2 <- ulam(
  alist(
    S ~ dbinom( N, p ) ,
    logit(p) <- a[tank] , 
    a[tank] ~ dnorm( a_bar, sigma ) ,
    a_bar ~ dnorm( 0, 1.5 ),
    sigma ~ dexp( 1 )
  ), data=dat, chains=4, log_lik = TRUE )
```
```{r compare the earlier model with the multi-level model}
compare(m13.1, m13.2)
```


```{r inspect the posterior - with memory}
precis(m13.2, depth=2)
```

```{r seeing the impact of adaptive regularisation more clearly}

# extract Stan samples
post <- extract.samples(m13.2)

# compute mean intercept for each tank
# also transform to probability with logistic
d$propsurv.est <- logistic( apply(post$a , 2 , mean ) )

# display raw proportions surviving in each tank
plot( d$propsurv , ylim=c(0,1) , pch=16 , xaxt="n",
      xlab="tank", ylab="proportion survival" , col=rangi2 )
axis( 1 , at=c(1,16,32,48),  labels=c(1,16,32,48) )

# overlay posterior means
points( d$propsurv.est )

# mark posterior mean probability across tanks
abline( h=mean(inv_logit(post$a_bar)) , lty=2 )

# draw vertical dividers between tank densities
abline( v=16.5 , lwd=0.5 )
abline( v=32.5 , lwd=0.5 )
text( 8 , 0 , "small tanks" )
text( 16+8 , 0 , "medium tanks" )
text( 32+8 , 0 , "large tanks" )

```
```{r inferred population distribution of tadpoles survival}
# show first 100 populations in the posterior 
plot(NULL, xlim=c(-3,4), ylim=c(0,0.35),
     xlab="log-odds survive", ylab="Density")

for(i in 1:2000)
  curve(dnorm(x, post$a_bar[i], post$sigma[i]), add=TRUE,
        col=col.alpha("black", 0.2) )

# sample 8000 imaginary tanks from the posterior distribution
# imaginary tank 1 is sampled from a different distribution from imaginary tank 2
# the parameters a_bar and sigma propagate uncertainty about the population down to the prediction of a new tank.
sim_tanks <- rnorm( 8000, post$a_bar, post$sigma ) 

# transform to probability and visualise
dens( inv_logit(sim_tanks), lwd=2, adj=0.1)
```
```{r check the values of a_bar and sigma of the posterior distribution}
tail(post$a_bar)
tail(post$sigma)
```

